[build-system]
requires = ["setuptools>=61.0"] 
build-backend = "setuptools.build_meta" 

[project]
name = "financial_data_analysis"  
version = "0.1.0" 
dependencies = [  
    "numpy",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["src"]
